### ISSUE TITLE
Routes that return files error occurs

### ISSUE THREAD

**Issue by fernandocristan** [Treblle/treblle-net-core#9]
In routes where a file is returned using the result file action, an error occurs and the file is not returned

Controller response
```C#
    //getFile
	return File(file.Content, file.ContentType, file.FileName);
``` 

Error

```
Unexpected character encountered while parsing value: %. Path '', line 0, position 0
```

Source code error:

```
Treblle.Net.Core.TrebllePayloadFactory.CreateAsync(HttpContext httpContext, Stream response, Int64 elapsedMilliseconds, Exception exception)
```

**Comment by cindreta** [comment]
Hey @fernandocristan Thx for reporting this! @m-jovanovic will take a look at this and I'm sure figure it out in no time.

Could uou provide you .NET version and SDK version. Thx

**Comment by fernandocristan** [comment]
Sure, here it is

- .NET: 6.0
- SDK: 1.0.10
